# -*- mode: makefile -*-
default: _complain_
include ./local.uses

TARFILE_LOCAL=${VIRGINS}/confuse-${LIBCONFUSE_VERSION}.tar.gz
TARFILE_URL  =http://www.intra2net.com/de/produkte/opensource/ftdi/TGZ/confuse-${LIBCONFUSE_VERSION}.tar.gz

CONFUSE_SRC_DIR   =${HERE}/confuse-${LIBCONFUSE_VERSION}
CONFUSE_BUILD_DIR =${HERE}/confuse-build

download:
	wget -O ${TARFILE_LOCAL} ${TARFILE_URL}

unpack:
	rm -rf ${CONFUSE_SRC_DIR}
	tar xfz ${TARFILE_LOCAL}

clean::
	rm -rf ${CONFUSE_SRC_DIR}

configure:
	rm -rf ${CONFUSE_BUILD_DIR} 
	mkdir ${CONFUSE_BUILD_DIR}
	cd ${CONFUSE_BUILD_DIR} && ${CONFUSE_SRC_DIR}/configure \
	   --prefix=${PREFIX} \
	   --exec-prefix=${EXEC_PREFIX}

clean::
	rm -rf ${CONFUSE_BUILD_DIR}

build:
	cd ${CONFUSE_BUILD_DIR} && ${MAKE}

install:
	cd ${CONFUSE_BUILD_DIR} && ${MAKE} install

all: unpack configure build install

_complain_:
	@echo ""
	@echo "Please try one of these targets: bootstrap, clean, configure, build, install"
	@echo " Or read the makefile and learn about the permutation test targets"
	@echo ""
	@echo "You also might find the download and unpack targets helpful."
	@echo ""
	@exit 1
