#!/bin/sh -e
# Run the autotools bootstrap sequence to create the configure script

if libtoolize --version >/dev/null 2>&1; then
	libtoolize="libtoolize"
elif glibtoolize --version >/dev/null 2>&1; then
	libtoolize="glibtoolize"
else
	echo "libtool is required" >&2
	exit 1
fi

# bootstrap the autotools
(
set -x
aclocal
${libtoolize} --automake --copy
autoconf
autoheader
automake --foreign --add-missing --copy
)

# AM_MAINTAINER_MODE requires SVN users provide --enable-maintainer-mode
# otherwise the documentation will fail to build due to missing version.texi
echo "Bootstrap complete; you can './configure --enable-maintainer-mode ....'"
