#!/bin/sh -e
# Run the autotools bootstrap sequence to create the configure script

# Stop execution as soon as we have an unknown command
set -e

if libtoolize --version >/dev/null 2>&1; then
	libtoolize="libtoolize"
elif glibtoolize --version >/dev/null 2>&1; then
	libtoolize="glibtoolize"
else
	echo "libtool is required" >&2
	exit 1
fi

# bootstrap the autotools
(
set -x
aclocal
${libtoolize} --automake --copy
autoconf
autoheader
automake --gnu --add-missing --copy
)

# AM_MAINTAINER_MODE requires --enable-maintainer-mode from everyone using
# current source snapshots (working from GIT, or some source snapshot, etc)
# otherwise the documentation will fail to build due to missing version.texi

if [ $1 == nosubmodule ]; then
    echo "Skipping submodule setup"
elif [ -z $1 ]; then 
    echo "Setting up submodules"
    git submodule init
    git submodule update
else
    echo "Argument to bootstrap is either no argument or nosubmodule"
    exit 1
fi

echo "Bootstrap complete. Quick start build instructions:"
echo "./configure --enable-maintainer-mode ...."
