# -*- mode: makefile -*-
default: _complain_

include ./local.uses

ifeq (x"$BUILD_SYSNAME",x"cygwin")
$(error Please use the Win32 specific port of LibUSB not the Unix version)
endif
ifeq (x"$BUILD_SYSNAME",x"mingw32")
$(error Please use the win32 specific port of LibUSB not the Unix version)
endif 

TARFILE_LOCAL    = ${VIRGINS}/libusb-${LIBUSB_VERSION_linux}.tar.bz2
TARFILE_URL      = http://downloads.sourceforge.net/libusb/libusb-${LIBUSB_VERSION_linux}.tar.gz

LIBUSB_SRC_DIR   = ${HERE}/libusb-${LIBUSB_VERSION}
LIBUSB_BUILD_DIR = ${HERE}/libusb-build

download:
	wget -O ${TARFILE_LOCAL} ${TARFILE_URL}

unpack:
	rm -rf ${LIBUSB_SRC_DIR}
	tar xfz ${TARFILE_LOCAL}

clean::
	rm -rf ${LIBUSB_SRC_DIR}

configure:
	rm -rf ${LIBUSB_BUILD_DIR}
	mkdir -p ${LIBUSB_BUILD_DIR}
	cd ${LIBUSB_BUILD_DIR} && ${LIBUSB_SRC_DIR}/configure \
		--prefix=${PREFIX} --exec-prefix=${EXEC_PREFIX}

clean::
	rm -rf ${LIBUSB_BUILD_DIR}

build:
	cd ${LIBUSB_BUILD_DIR} && ${MAKE}

install: 
	cd ${LIBUSB_BUILD_DIR} && ${MAKE} install

all: unpack configure build install

.PHONY: install

_complain_:
	@echo ""
	@echo "Please try one of these targets: bootstrap, clean, configure, build, install"
	@echo " Or read the makefile and learn about the permutation test targets"
	@echo ""
	@echo "You also might find the download and unpack targets helpful."
	@echo ""
	@exit 1
