.TH "OPENOCD" "1" "May 03, 2007" "" ""
.SH "NAME"
openocd \- A free and open on\-chip debugging, in\-system programming and
boundary\-scan testing tool for ARM systems (currently ARM7/9 and XScale, Cortex\-M3 support to be merged)
.SH "SYNOPSIS"
.B openocd \fR[\fB\-fdlh\fR] [\fB\-\-file\fR <filename>] [\fB\-\-debug\fR <debuglevel>] [\fB\-\-log_output\fR <filename>] [\fB\-\-help]
.SH "DESCRIPTION"
.B OpenOCD
is an on\-chip debugging, in\-system programming and boundary\-scan
testing tool for ARM systems.
.PP 
The debugger uses an IEEE 1149\-1 compliant JTAG TAP bus master to access
on\-chip debug functionality available on ARM7/9 and XScale based
microcontrollers / system\-on\-chip solutions.
.PP 
User interaction is realized through a telnet command line interface and
a gdb (the GNU debugger) remote protocol server.
.PP 
OpenOCD supports various different types of JTAG interfaces/programmers:
  * Parallel port wigglers
  * Amontec JTAG Accelerator
  * FTDI FT2232 based USB devices
  * USBJTAG
  * OOCD\-Link
  * Amontec JTAGkey
  * Amontec JTAGkey\-Tiny
  * Olimex ARM\-USB\-OCD
  * eVerve Signalyzer
  * ... other FT2232 based dongles
.PP 
It also supports a number of different ARM7/9 cores:
  * ARM7TDMI(\-s)
  * ARM720t
  * ARM9TDMI
  * ARM920t
  * ARM922t
  * ARM926ej\-s
  * ARM966e
.PP 
Support for Intel XScale CPUs is also included:
  * PXA25x
  * IXP42x

PXA27x debugging should be similar to the PXA25x but fails in the current
version of OpenOCD.
.SH "OPTIONS"
.TP 
.B "\-f, \-\-file <filename>"
Use configuration file
.BR <filename> .
If this option is omitted, the config file
.B openocd.cfg
in the current working directory will be used.
.TP 
.B "\-d, \-\-debug <debuglevel>"
Set debug level. Possible values are:
.br 
.RB "  * " 0 " (errors)"
.br 
.RB "  * " 1 " (warnings)"
.br 
.RB "  * " 2 " (informational messages)"
.br 
.RB "  * " 3 " (debug messages)"
.br 
The default level is
.BR 2 .
.TP 
.B "\-l, \-\-log_output <filename>"
Redirect log output to the file
.BR <filename> .
Per default the log output is printed on
.BR stderr .
.TP 
.B "\-h, \-\-help"
Show a help text and exit.
.\".TP 
.\".B "\-v, \-\-version"
.\"Show version information and exit.
.SH "BUGS"
Please report any bugs at
.B http://developer.berlios.de/bugs/?group_id=4148
or on the mailing list
.BR openocd\-development@lists.berlios.de .
.SH "LICENCE"
.B OpenOCD
is covered by the GNU General Public License (GPL), version 2 or later.
.\"
.SH "SEE ALSO"

.SH "AUTHORS"
Dominic Rath <Dominic.Rath@gmx.de>
.br 
Magnus Lundin <lundin@mlu.mine.nu>
.br 
Michael Fischer <fischermi@t\-online.de>
.br 
Spencer Oliver <spen@spen\-soft.co.uk>
.br 
and others
.PP 
This manual page was written by Uwe Hermann <uwe@hermann\-uwe.de>.
It is licensed under the terms of the GNU GPL (v2 or later).
