#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char **argv)
{
	int c;
	unsigned int n;
	char *name;

	if (argc == 1) {
		fprintf(stderr, "bin2char <varname>\n");
		fprintf(stderr, "read from standard input and write a char"
		    " array out to standard output\n");
		exit(1);
	}

	n = 0;
	name = argv[1];
	fprintf(stdout, "/* autogenerated from %s */\n", argv[0]);
	fprintf(stdout, "unsigned const char %s[] = {\n", name);
	while ((c = getc(stdin)) != EOF) {
		fprintf(stdout, "0x%02x,", c & 0xff);
		if ((++n % 16) == 0)
			fprintf(stdout, "\n");
	}
	fprintf(stdout, "0 /* terminate with a nil */};\n");
	fprintf(stdout, "unsigned int %s_len = %u;\n", name, n);
	return 0;
}
