#---------------------------------------------------------------------
#-- OpenOCD Reset Init Script for IXP42x box with RedBoot
#---------------------------------------------------------------------

#debug 3

#- Let U-Boot setup the box ------------------------------------------
poll
resume 0x40
sleep 2000
halt
wait_halt 20

#- Reverse RedBoot crap ----------------------------------------------
xscale icache disable
xscale dcache disable
xscale mmu disable

#- Check for flash ---------------------------------------------------
flash banks
flash probe 0
flash probe 1
#flash protect_check 0
#flash protect_check 1
#flash erase_check 0
#flash erase_check 1
#flash info 0
#flash info 1

#- Bootloader --------------------------------------------------------
#flash erase 0 0 2
#flash write 0 //devboc/homes/src/denx/u-boot-git/u-boot.bin 0x00000 bin

#- Kernel Image ------------------------------------------------------
#flash erase 0 3 23
#flash write 0 //devbox/homes/src/pengutronics/ptxdist-project/images/linuximage 0x60000 bin
